export const data = {
  bio: {
    name: 'Sthefano Carvalho',
    tagline: 'Full Stack Developer',
    email: 'sthefano@masteradin.com',
    github: 'https://github.com/sthefanoc',
    website: 'https://www.sthefanoc.com',
    linkedin: 'https://linkedin.com/in/sthefanocarvalho',
    objective: 'Build amazing tools with the best technologies.',
  },
  skills: ['Python', 'Javascript', 'HTML', 'CSS', 'ReactJS', 'NodeJS'],
  positions: [
    {
      id: '1',
      title: 'Full Stack Developer',
      company: 'SthefanoC.com',
      startDate: '2020-01-01',
      endDate: null,
      employmentType: 'PART_TIME',
      location: 'São Paulo, Brazil',
      achievements: [
        'Automation Tools Development using Python, deploying scripts on Heroku, Google Cloud Platform and Python Anywhere',
        'Website development using HTML, CSS and Javascript, deploying on Github Pages, Netlify and cPanel hosting platforms',
        'Frontend Development using ReactJs, GatsbyJS and NextJS for interface, Redux for state management',
        'Backend Development using NodeJs, Express, Django, Flask and Firebase',
        'Mobile Development using Hybrid App Development technologies, such as React Native and PWA',
      ],
    },
    {
      id: '2',
      title: 'Managing Director | Co-founder',
      company: 'Masteradin',
      startDate: '2018-11-01',
      endDate: null,
      employmentType: 'FULL_TIME',
      location: 'São Paulo, Brazil',
      achievements: [
        'Process Automation using Selenium',
        'E-commerce website performance evaluation: technical and strategic',
        'Business Analysis using Growth Hacking Techniques',
        'SEM (Google Ads), SEO (Content and Tech), Backlink Acquisition, Socila Media (Whatsapp & Instagram)',
      ],
    },
    {
      id: '3',
      title: 'Customer Development Analyst',
      company: 'Unilever',
      startDate: '2015-01-01',
      endDate: '2018-09-01',
      employmentType: 'FULL_TIME',
      location: 'São Paulo, Brazil',
      achievements: [
        'Website implementation',
        'Contract Management',
        'Investment Analysis',
        'Financial Management',
        'Training and Team Leadership'
      ],
    },
    {
      id: '4',
      title: 'Customer Development Analyst',
      company: 'Unilever',
      startDate: '2014-02-01',
      endDate: '2015-02-01',
      employmentType: 'FULL_TIME',
      location: 'São Paulo, Brazil',
      achievements: [
        'Performance KPIs',
        'Financial Management',
        'Strategy and relationship with Distributors',
        'Innovation Planning'
      ],
    },
    {
      id: '5',
      title: 'Trademarketing Intern',
      company: 'Unilever',
      startDate: '2012-01-01',
      endDate: '2013-12-01',
      employmentType: 'FULL_TIME',
      location: 'São Paulo, Brazil',
      achievements: [
        'Responsible for organizing events and store promotional campaigns and programs.',
        'Responsible for the development and implementation of Visibility Materials.',
      ],
    },
  ],
};